#FROM ubuntu
FROM yolo

RUN apt-get update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt install -y python-opencv python-pip cmake vim-tiny mosquitto-clients libopencv-dev libjpeg-dev
RUN pip install paho-mqtt
RUN pip install numpy
RUN pip install face_recognition

WORKDIR /
COPY detector.py /

CMD python detector.py

